language: node_js
node_js:
  - '0.12'
  - '4.2'

cache:
  directories:
    - node_modules

script:
- npm test

deploy:
  provider: npm
  email: dev@developmentseed.org
  api_key:
    secure: kcQg9RhrYFNlGPuwdTuPQa2OWFjHUACN/QERjgbziIExrfFIKuFXy5iLpgGB9ox8FMBNwFEzseSh9xK+NR7LrQ6UWSMm7mtEgBZ4iZM5NJLm/GL/PbTMVKvdMNmuOEhgyplGEy9ELcfWNdiHklXVf4HyZ2nKJQ9bLR/JMYoliSLc2xdppwzAwJtXhPBJsGKE9n+M6gvVLT9KoNWlnegledhjHZ2yZM4/HyTZOGtfM6ZQUL5zhRdfe3/VT5zPHxlyce3Kz5ygcmbadigo6BIYKTf41IyKpud/dQYRQ5tGhSm+U3DlxmfZIM/WfrU2NPjuEwiFkgjnzSJRGpRfkOtWkKfExTKH8xmMDT0Py1yYjoYqMve04izOZTDE4jh40ae6qYTFYiy9fABimijpK2tTpwAezWhNIK+q6r6HfLEyN1eW7AdCCWE3AJtoKNkk17zxWRAySzaRW2nbxQT/BiJ4bQGlpIBvUM9g+F4tmb04xkZPV+uF0MGE1ypusM+g6Gv73XqFDue7NB79DP79VPErZXQHRJcWiRItW+339uXKIYqdx9VeVRcJfBZXTGJEDilqPIP+73z5QcwknLFa8vBWyXuFfns7t5/Bae+rhxplmc+LjrKkH2mL/+4hw+JUU1xSqPOkCKl/UTZsM81RdjtX1scMfMNFmUwI2fBGHmcX98M=
  on:
    tags: true
    repo: developmentseed/collecticons-processor
